workaround for error:0308010C:digital envelope routines::unsupported
This was caused by using node 17.  Could also switch to node 16 LTS
version.  Solution found here:
https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported
https://github.com/webpack/webpack/issues/14532

The error looks like this:

Starting the development server...

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:135:10)
    at module.exports (/Users/kai/projects/roxana/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/kai/projects/roxana/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/Users/kai/projects/roxana/node_modules/webpack/lib/NormalModule.js:471:10)
    at /Users/kai/projects/roxana/node_modules/webpack/lib/NormalModule.js:503:5
    at /Users/kai/projects/roxana/node_modules/webpack/lib/NormalModule.js:358:12
    at /Users/kai/projects/roxana/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/kai/projects/roxana/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/Users/kai/projects/roxana/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
/Users/kai/projects/roxana/node_modules/react-scripts/scripts/start.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:135:10)
    at module.exports (/Users/kai/projects/roxana/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/kai/projects/roxana/node_modules/webpack/lib/NormalModule.js:417:16)
    at /Users/kai/projects/roxana/node_modules/webpack/lib/NormalModule.js:452:10
    at /Users/kai/projects/roxana/node_modules/webpack/lib/NormalModule.js:323:13
    at /Users/kai/projects/roxana/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/kai/projects/roxana/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/Users/kai/projects/roxana/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /Users/kai/projects/roxana/node_modules/babel-loader/lib/index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.7.1